[package]
name = "dscale"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
indicatif = "0.18.3"
log = { version = "0.4.29", features = ["release_max_level_info"] }
mimalloc = "0.1.48"
rand = "0.9.2"
rand_distr = "0.5.1"
